apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: default

patches:
- target:
    kind: Deployment
    name: nginx
  patch: |-
    apiVersion: app:v1
    kind: deployment
    metadata:
      name: nginx
    spec:
      replicas: 2